#!/usr/bin/env bash

set -e
rm -rf ~/.vim_runtime || true
git clone --depth=1 https://github.com/Willie169/vim-config.git ~/.vim_runtime
cd ~/.vim_runtime/pack/my-plugins/start
git clone --depth=1 https://github.com/lilydjwg/fcitx.vim.git
git clone --depth=1 https://github.com/Willie169/termux-clipboard.git
git clone --depth=1 https://github.com/jasonccox/vim-wayland-clipboard.git
cd ~
echo '" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim
" See ~/.vim_runtime/README.md "Customization" for further options.

set runtimepath+=~/.vim_runtime
set packpath+=~/.vim_runtime
source ~/.vim_runtime/basic.vim

try
  source ~/.vim_runtime/my_configs.vim
catch
endtry
' >~/.vimrc
echo "Installed successfully!"
