#!/usr/bin/env bash

set -e
cd ~/.vim_runtime
git reset --hard
git pull --rebase
git clean -fd
cd ~/.vim_runtime/pack/my-plugins/start
for repo in fcitx.vim termux-clipboard vim-wayland-clipboard; do
	cd ~/.vim_runtime/pack/my-plugins/start/"$repo"
	git reset --hard
	git pull --rebase
	git clean -fd
done
cd ~
echo '" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim
" See ~/.vim_runtime/README.md "How to include your own stuff" for further options.

set runtimepath+=~/.vim_runtime
set packpath+=~/.vim_runtime
source ~/.vim_runtime/basic.vim

try
  source ~/.vim_runtime/my_configs.vim
catch
endtry
' >~/.vimrc
echo "Updated successfully!"
