" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim
" See ~/.vim_runtime/README.md "Customization" for further options.

set runtimepath+=~/.vim_runtime
set packpath+=~/.vim_runtime
source ~/.vim_runtime/basic.vim

try
    source ~/.vim_runtime/my_configs.vim
catch
endtry
